# Replace the text below to customize your site
site_name: Fab Foundation Poland
site_description: Fab Foundation Poland
site_author: Judy Curie
copyright: Copyright 2023 Judy Curie - Creative Commons Attribution Non Commercial

site_url: http://fibasile.fabcloud.io/fabacademy-student-judycurie/

extra:
  # Set your own social media below (or remove)
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/judycurie/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/judyta.cichocka
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/judycurie
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/judyta-cichocka-6992a854/
theme:
  name: material
  


  font:
    # See available fonts at https://fonts.google.com/
    # My favourites: Inconsolata,  IBM Plex Mono, Chakra Petch, Exo, Didact Gothic, Exo
    text: Roboto Mono
    code: Ubuntu Mono

  logo: images/icon.jpg
  favicon: images/icon.jpg
  features:
    - navigation.tabs
    - navigation.instant
  font:
    # See available fonts at https://fonts.google.com/
    # My favourites: Inconsolata,  IBM Plex Mono, Chakra Petch, Exo, Didact Gothic, Exo
    text: Roboto Mono
    code: Ubuntu Mono

  logo: assets/ffp-icon.jpg
  favicon: assets/ffp-icon.jpg
  features:
    - navigation.tabs
    - navigation.instant

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      # Read more: https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/options/#enabled
      enabled: !ENV [ENABLED_GIT_REVISION_DATE, False]

markdown_extensions:
  - extra
  - smarty
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
extra_css:
  - stylesheets/extra.css
